### ISSUE TITLE
no load module oracledb

### ISSUE THREAD

**Issue by SchweinchenFuntik** [mickeypearce/oradew-vscode#14]
I'm trying to create a new workspace. But I get an error. In this case, oracledb is installed, and the extensions [Language PL/SQL](https://marketplace.visualstudio.com/items?itemName=xyz.plsql-language#review-details,) works.

```
> Executing task: node /home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/gulp/bin/gulp.js --cwd /home/funtik/Projects/fsharpProject/plsql --gulpfile /home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/out/gulpfile.js --color true --silent true initProject <

/home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/oracledb/lib/oracledb.js:68
      throw new Error(nodbUtil.getErrorMessage('NJS-045', nodeInfo));
      ^

Error: NJS-045: cannot load the oracledb add-on binary for Node.js 8.14.0 (linux, x64)
Cannot load /home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/oracledb/build/Release/oracledb.node
/home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/oracledb/build/Release/oracledb.node: invalid ELF header
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

    at Object.<anonymous> (/home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/oracledb/lib/oracledb.js:68:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:653:30)
Процесс терминала завершен с кодом выхода: 1
```

**Comment by mickeypearce** [comment]
Hi.
Oracle driver (node-oracledb@2.2.0) in extension is precompiled with "node-v59 (Node.js 9) - win32 - x64 (64bit)" binary package.

Oracle client library architecture (instantclient), Node.js version, OS and architecture must match precompiled configuration otherwise node-oracledb drivers have to be rebuild:

```bash
## Rebuild Oracle drivers 
## (go to your ext folder /home/funtik/.vscode/extensions/mp.oradew-vscode-0.1.6/):
> npm rebuild
```
This will recompile the drivers for your system configuration...

**Comment by SchweinchenFuntik** [comment]
thank you sorry for not answering for a long time

**Comment by mickeypearce** [comment]
No problem!
