### ISSUE TITLE
Error when initializing workspace.

### ISSUE THREAD

**Issue by GAZ082** [mickeypearce/oradew-vscode#5]
Hey there. I'm getting this when initializing the workspace:
```
Error: ENOENT: no such file or directory, uv_chdir
    at Liftoff.handleArguments (C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\gulp\bin\gulp.js:108:13)
    at Liftoff.execute (C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\liftoff\index.js:203:12)
    at module.exports (C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\liftoff\index.js:195:5)
    at C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\liftoff\index.js:165:9
    at C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\v8flags\index.js:110:14
    at C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\v8flags\index.js:38:12
    at C:\Users\x\.vscode\extensions\mp.oradew-vscode-0.0.4\node_modules\v8flags\index.js:49:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Any tips? Thanks!

**Comment by mickeypearce** [comment]
Hey @GAZ082, thanks for reaching out.

Can you please tell your OS and Node.js version?

**Comment by mickeypearce** [comment]
Looks like Gulp fails to change its working directory (cwd) to your current working folder.

Can you post output from terminal just above your error, when it reads something like:

`> Executing task: C:\Users\xxx\mp.oradew-vscode-0.0.4\out\gulp.cmd --cwd c:\Users\xxx\oradew-test --gulpfile C:\xxx\mp.oradew-vscode-0.0.4\out\gulpfile.js --silent true --color true initProject <`

and check if directory after --cwd actually exists.

**Comment by mickeypearce** [comment]
This is a problem with spaces in workspace folder.
